services:
  - type: web
    name: poker-range-classifier
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements_py37.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.7.16
    healthCheckPath: /
    autoDeploy: true
