services:
  - type: web
    name: poker-range-classifier
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install numpy==1.22.4 pandas==1.4.4
      pip install scikit-learn==1.3.0
      pip install matplotlib==3.5.3 seaborn==0.11.2 tqdm==4.64.1 joblib==1.1.1
      pip install flask==2.2.3 gunicorn==20.1.0
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /
    autoDeploy: true
